// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Currency struct {
	ID        int64
	Code      string
	Name      string
	Symbol    string
	CreatedAt pgtype.Timestamp
	IsDeleted bool
}

type Expense struct {
	ID          int64
	GroupID     int64
	Type        int16
	Name        string
	Description string
	Amount      pgtype.Numeric
	CurrencyID  int64
	ExpenseAt   pgtype.Timestamp
	CreatedAt   pgtype.Timestamp
	IsDeleted   bool
}

type ExpensePayer struct {
	ID        int64
	ExpenseID int64
	UserID    int64
	Amount    pgtype.Numeric
	CreatedAt pgtype.Timestamp
}

type ExpenseShare struct {
	ID        int64
	ExpenseID int64
	UserID    int64
	Amount    pgtype.Numeric
	CreatedAt pgtype.Timestamp
}

type Group struct {
	ID          int64
	Name        string
	InviteToken string
	CreatedAt   pgtype.Timestamp
	IsDeleted   bool
}

type User struct {
	ID        int64
	Username  string
	Email     string
	Password  string
	CreatedAt pgtype.Timestamp
	IsDeleted bool
}

type UserCurrencyPreference struct {
	ID         int64
	UserID     int64
	CurrencyID int64
	UseCount   int32
	CreatedAt  pgtype.Timestamp
}

type UserGroup struct {
	ID        int64
	UserID    int64
	GroupID   int64
	CreatedAt pgtype.Timestamp
	IsDeleted bool
}
