// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Currency struct {
	ID     int64  `json:"id"`
	Code   string `json:"code"`
	Name   string `json:"name"`
	Symbol string `json:"symbol"`
}

type Expense struct {
	ID        int64          `json:"id"`
	Amount    pgtype.Numeric `json:"amount"`
	Currency  *Currency      `json:"currency"`
	ExpenseAt time.Time      `json:"expenseAt"`
	Payers    []*Share       `json:"payers"`
	Shares    []*Share       `json:"shares"`
}

type ExpenseInput struct {
	Amount     pgtype.Numeric `json:"amount"`
	CurrencyID int64          `json:"currencyId"`
	ExpenseAt  time.Time      `json:"expenseAt"`
	Payers     []*ShareInput  `json:"payers"`
	Shares     []*ShareInput  `json:"shares"`
}

type ExpenseSummary struct {
	Expenses []*Expense   `json:"expenses"`
	Owes     []*OweDetail `json:"owes"`
	Owed     []*OweDetail `json:"owed"`
}

type Group struct {
	ID      int64   `json:"id"`
	Name    string  `json:"name"`
	Members []*User `json:"members"`
}

type Mutation struct {
}

type OweDetail struct {
	User   *User          `json:"user"`
	Amount pgtype.Numeric `json:"amount"`
}

type Query struct {
}

type Share struct {
	User   *User          `json:"user"`
	Amount pgtype.Numeric `json:"amount"`
}

type ShareInput struct {
	UserID int64          `json:"userId"`
	Amount pgtype.Numeric `json:"amount"`
}

type Subscription struct {
}

type User struct {
	ID    int64  `json:"id"`
	Name  string `json:"name"`
	Token string `json:"token"`
}
