// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"

	"github.com/shopspring/decimal"
)

type ConversionDetails struct {
	SourceCurrency *Currency       `json:"sourceCurrency"`
	SourceAmount   decimal.Decimal `json:"sourceAmount"`
	Rate           decimal.Decimal `json:"rate"`
}

type ConversionInput struct {
	Name             string          `json:"name"`
	Description      string          `json:"description"`
	SourceAmount     decimal.Decimal `json:"sourceAmount"`
	SourceCurrencyID int64           `json:"sourceCurrencyId"`
	TargetAmount     decimal.Decimal `json:"targetAmount"`
	TargetCurrencyID int64           `json:"targetCurrencyId"`
	ExpenseAt        time.Time       `json:"expenseAt"`
	DebtorID         int64           `json:"debtorId"`
	CreditorID       int64           `json:"creditorId"`
}

type Currency struct {
	ID     int64  `json:"id"`
	Code   string `json:"code"`
	Name   string `json:"name"`
	Symbol string `json:"symbol"`
}

type ExchangeRate struct {
	Code string          `json:"code"`
	Rate decimal.Decimal `json:"rate"`
}

type ExchangeRateSnapshot struct {
	Base                  string          `json:"base"`
	Rates                 []*ExchangeRate `json:"rates"`
	FetchedAt             time.Time       `json:"fetchedAt"`
	UnsupportedCurrencies []string        `json:"unsupportedCurrencies"`
}

type Expense struct {
	ID                int64              `json:"id"`
	Type              string             `json:"type"`
	Name              string             `json:"name"`
	Description       string             `json:"description"`
	Amount            decimal.Decimal    `json:"amount"`
	Currency          *Currency          `json:"currency"`
	ExpenseAt         time.Time          `json:"expenseAt"`
	Payers            []*Share           `json:"payers"`
	Shares            []*Share           `json:"shares"`
	ConversionDetails *ConversionDetails `json:"conversionDetails,omitempty"`
}

type ExpenseInput struct {
	Name        string          `json:"name"`
	Description string          `json:"description"`
	Amount      decimal.Decimal `json:"amount"`
	Type        string          `json:"type"`
	CurrencyID  int64           `json:"currencyId"`
	ExpenseAt   time.Time       `json:"expenseAt"`
	Payers      []*ShareInput   `json:"payers"`
	Shares      []*ShareInput   `json:"shares"`
}

type ExpenseSummary struct {
	Expenses []*Expense `json:"expenses"`
	Owes     []*Owe     `json:"owes"`
	Owed     []*Owe     `json:"owed"`
}

type Group struct {
	ID             int64       `json:"id"`
	Name           string      `json:"name"`
	InviteToken    string      `json:"inviteToken"`
	Members        []*User     `json:"members"`
	UsedCurrencies []*Currency `json:"usedCurrencies"`
}

type Mutation struct {
}

type Owe struct {
	User     *User           `json:"user"`
	Amount   decimal.Decimal `json:"amount"`
	Currency *Currency       `json:"currency"`
}

type Query struct {
}

type RedactedGroup struct {
	Name    string  `json:"name"`
	Members []*User `json:"members"`
}

type RepaymentInput struct {
	Name        string          `json:"name"`
	Description string          `json:"description"`
	Amount      decimal.Decimal `json:"amount"`
	Type        string          `json:"type"`
	CurrencyID  int64           `json:"currencyId"`
	ExpenseAt   time.Time       `json:"expenseAt"`
	Debtor      int64           `json:"debtor"`
	Creditor    int64           `json:"creditor"`
}

type Share struct {
	User   *User           `json:"user"`
	Amount decimal.Decimal `json:"amount"`
}

type ShareInput struct {
	UserID int64           `json:"userId"`
	Amount decimal.Decimal `json:"amount"`
}

type Subscription struct {
}

type User struct {
	ID    int64  `json:"id"`
	Name  string `json:"name"`
	Token string `json:"token"`
}
