// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"

	"github.com/shopspring/decimal"
)

type Currency struct {
	ID     int64  `json:"id"`
	Code   string `json:"code"`
	Name   string `json:"name"`
	Symbol string `json:"symbol"`
}

type Expense struct {
	ID        int64           `json:"id"`
	Type      string          `json:"type"`
	Amount    decimal.Decimal `json:"amount"`
	Currency  *Currency       `json:"currency"`
	ExpenseAt time.Time       `json:"expenseAt"`
	Payers    []*Share        `json:"payers"`
	Shares    []*Share        `json:"shares"`
}

type ExpenseInput struct {
	Amount     decimal.Decimal `json:"amount"`
	CurrencyID int64           `json:"currencyId"`
	ExpenseAt  time.Time       `json:"expenseAt"`
	Payers     []*ShareInput   `json:"payers"`
	Shares     []*ShareInput   `json:"shares"`
}

type ExpenseSummary struct {
	Expenses []*Expense `json:"expenses"`
	Owes     []*Owe     `json:"owes"`
	Owed     []*Owe     `json:"owed"`
}

type Group struct {
	ID      int64   `json:"id"`
	Name    string  `json:"name"`
	Members []*User `json:"members"`
}

type Mutation struct {
}

type Owe struct {
	User     *User           `json:"user"`
	Amount   decimal.Decimal `json:"amount"`
	Currency *Currency       `json:"currency"`
}

type Query struct {
}

type RepaymentInput struct {
	Amount     decimal.Decimal `json:"amount"`
	CurrencyID int64           `json:"currencyId"`
	ExpenseAt  time.Time       `json:"expenseAt"`
	Debtor     int64           `json:"debtor"`
	Creditor   int64           `json:"creditor"`
}

type Share struct {
	User   *User           `json:"user"`
	Amount decimal.Decimal `json:"amount"`
}

type ShareInput struct {
	UserID int64           `json:"userId"`
	Amount decimal.Decimal `json:"amount"`
}

type Subscription struct {
}

type User struct {
	ID    int64  `json:"id"`
	Name  string `json:"name"`
	Token string `json:"token"`
}
