input RepaymentInput {
    name: String!
    description: String!
    amount: Decimal!
    type: String!
    currencyId: ID!
    expenseAt: Time!
    debtor: ID!
    creditor: ID!
}

input ExpenseInput {
    name: String!
    description: String!
    amount: Decimal!
    type: String!
    currencyId: ID!
    expenseAt: Time!
    payers: [ShareInput!]!
    shares: [ShareInput!]!
}

input ShareInput {
    userId: ID!
    amount: Decimal!
}

input ConversionInput {
    name: String!
    description: String!
    sourceAmount: Decimal!
    sourceCurrencyId: ID!
    targetAmount: Decimal!
    targetCurrencyId: ID!
    expenseAt: Time!
    debtorId: ID!
    creditorId: ID!
}