package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"fmt"

	"github.com/raythx98/go-dutch/graphql/model"
)

// ExpenseAdded is the resolver for the expenseAdded field.
func (r *subscriptionResolver) ExpenseAdded(ctx context.Context, userID int64) (<-chan *model.Expense, error) {
	panic(fmt.Errorf("not implemented: ExpenseAdded - expenseAdded"))
}

// ExpenseUpdated is the resolver for the expenseUpdated field.
func (r *subscriptionResolver) ExpenseUpdated(ctx context.Context, userID int64) (<-chan *model.Expense, error) {
	panic(fmt.Errorf("not implemented: ExpenseUpdated - expenseUpdated"))
}

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type subscriptionResolver struct{ *Resolver }
