package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"

	"github.com/raythx98/go-dutch/graphql/model"
)

// Members is the resolver for the members field.
func (r *groupResolver) Members(ctx context.Context, obj *model.Group) ([]*model.User, error) {
	members, err := r.DbQuery.GetGroupMembers(ctx, obj.ID)
	if err != nil {
		return nil, err
	}

	response := make([]*model.User, 0)
	for _, member := range members {
		response = append(response, &model.User{
			ID:   member.ID,
			Name: member.Username,
		})
	}

	return response, nil
}

// UsedCurrencies is the resolver for the usedCurrencies field.
func (r *groupResolver) UsedCurrencies(ctx context.Context, obj *model.Group) ([]*model.Currency, error) {
	currencies, err := r.DbQuery.GetGroupCurrencies(ctx, obj.ID)
	if err != nil {
		return nil, err
	}

	response := make([]*model.Currency, 0)
	for _, currency := range currencies {
		response = append(response, &model.Currency{
			ID:     currency.ID,
			Code:   currency.Code,
			Name:   currency.Name,
			Symbol: currency.Symbol,
		})
	}

	return response, nil
}

// Group returns GroupResolver implementation.
func (r *Resolver) Group() GroupResolver { return &groupResolver{r} }

type groupResolver struct{ *Resolver }
